- hosts: localhost
  gather_facts: false
  vars_files:
    - config/deploy_ec2_config.yml
  tasks:    
    -   name: Create security group
        ec2_group:
            name: "{{ project_name }}_security_group"
            description: "{{ project_name }} security group"
            rules:
                - proto: tcp
                  from_port: 22
                  to_port: 22
                  cidr_ip: 0.0.0.0/0
                  rule_desc: allow all on port 22
                - proto: tcp
                  from_port: 80
                  to_port: 80
                  cidr_ip: 0.0.0.0/0
                  rule_desc: allow all on port 80
                - proto: tcp
                  from_port: 443
                  to_port: 443
                  cidr_ip: 0.0.0.0/0
                  rule_desc: allow all on port 443
            rules_egress:
                - proto: all                  
                  cidr_ip: 0.0.0.0/0
                  rule_desc: allow outbound to any port and machine
        register: basic_firewall
        
  tasks:
    -   name: Create an EC2 key
        ec2_key:
            name: "{{ project_name }}_key"
        register: ec2_key
        
  tasks:
    -   name: Save private key to be used later
        copy:
            content: ec2_key.key.private_key
            dest: "./aws-private.pem"
            mode: 0600
        when: ec2_key.changed
        
        
  tasks:
    -   name: Create an EC2 instance
        ec2:
            key_name: "{{ project_name }}_key"            
            group: "{{ project_name }}_security_group"
            instance_type: "{{ instance_type }}"
            image: "{{ ami_image }}"
            wait: yes
            count: 1            
            assign_public_ip: yes
        register: ec2