- hosts: localhost
  vars_files:
    - config/config.yml
  tasks:    
    -   name: Create security group
        ec2_group:
            name: "{{ project_name }}_security_group"
            description: "{{ project_name }} security group"
            rules:
                - proto: tcp
                  type: ssh
                  from_port: 22
                  to_port: 22
                  cidr_ip: 0.0.0.0/0
                - proto: tcp
                  type: http
                  from_port: 80
                  to_port: 80
                  cidr_ip: 0.0.0.0/0
                - proto: tcp
                  type: https
                  from_port: 443
                  to_port: 443
                  cidr_ip: 0.0.0.0/0
            rules_egress:
                - proto: all
                  type: all
                  cidr_ip: 0.0.0.0/0
        register: basic_firewall