---
#Provision EC2 instances & install Spark

- hosts: localhost
  roles: 
    - { role: provisionec2, tags: ["provision"] }

- hosts: sparkmaster
  roles: 
    - { role: sparkmaster, tags: ["provision"] }    
    
- hosts: sparkworker
  roles: 
    - { role: sparkworker, tags: ["provision"] }

#Shutdown EC2 instances 

- hosts: localhost
  roles:     
    - { role: shutdownec2, tags: ["shutdown"] }   
        
#Terminate EC2 instances 

- hosts: localhost
  roles: 
    - { role: terminateec2, tags: ["terminate"] }