---
#Provision EC2 instances & install Spark

- hosts: localhost
  gather_facts: False
  roles: 
    - { role: provisionec2, tags: ["provision"] }
        

- hosts: sparkmaster
  gather_facts: False
  roles: 
    - { role: sparkmaster, tags: ["provision"] }    
        
  
- hosts: sparkworker
  gather_facts: False
  roles: 
    - { role: sparkworker, tags: ["provision"] }
        
  
#Shutdown EC2 instances 

- hosts: localhost
  gather_facts: False
  roles:     
    - { role: shutdownec2, tags: ["shutdown"] }   
        
#Terminate EC2 instances 

- hosts: localhost
  gather_facts: False
  roles: 
    - { role: terminateec2, tags: ["terminate"] }