# Project name
project_name: ec2_spark_deploy
ami_image: ami-d874e0a0
instance_type: t2.micro
region: us-west-2
hostpath: hosts

spark_download: https://www.apache.org/dyn/closer.lua/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz
install_temp_dir:/tmp
spark_archive:/spark_arc
install_dir:/opt
spark_installation_dir:/spark
