swagger: "2.0"
info: 
  version: "0.0.1"
  title: "filter"
  description: "A simple service to filter data"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Sandeep Khandelwal"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /filter:
    get: 
      description: "Returns filtered data based on criteria"
      operationId: filter
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "Filtered Data"
      parameters:
        - in: query
          name: "criteria"
          required: "true"
          type: "string"
          description: "The filter criteria"
