swagger: "2.0"
info: 
  version: "0.0.1"
  title: "filter"
  description: "A simple service to filter data as an example of using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST Service Example"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /filter:
    get: 
      description: "Returns filtered data from the hosting server"
      operationId: filter
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "Filtered Data"
      parameters:
        - in: query
          name: criteria
          required: true
          schema:
            type: string
          description: The filter criteria. Supporrted critea are positive, negative, odd and even
