---
#Shutdown EC2 instances
        
    -   name: Gather EC2 facts.
        ec2_remote_facts:
            region: "{{ region }}"
        register: ec2_facts

    -   name: Debug
        debug:
            msg: "{{ ec2_facts }}"        
    