project_name: ec2_spark_deploy
env: stg
hostpath: inventory/hosts
ansible_ssh_private_key_file: "{{ project_name }}_{{ env }}_key-private.pem"
ansible_ssh_user: ubuntu
ansible_python_interpreter: /usr/bin/python3