---
swagger: "2.0"
info:
  description: "A simple service to filter data"
  version: "0.0.1"
  title: "filter"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Sandeep Khandelwal"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /filter:
    get:
      description: "Returns filtered data based on criteria"
      operationId: "filter"
      produces:
      - "application/json"
      parameters:
      - name: "criteria"
        in: "query"
        description: "The filter criteria"
        required: true
        type: "string"
      responses:
        200:
          description: "Filtered Data"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions: {}
